# NOTE: this file is overridden for development by docker-compose.override.yml
version: '3.8'

services:
  # NOTE: this does not work on m1 macs, cypress is working on it, but it seems like it depends upon chrome creating a linux/arm64 release, which is unlikely
  cypress:
    image: cypress/included:10.3.0
    command: --record
    platform: "linux/amd64"
    profiles: ['test']
      #entrypoint: cypress open --project /
    depends_on:
      - web
    environment:
      CYPRESS_baseUrl: http://web:3000 # this bypasses nginx, I'm not sure if this is a good idea
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY}
    working_dir: /e2e
    volumes:
      #- ./:/e2e
      # NOTE: cypress needs the .git directory to show commit info on the dashboard
      - ./.git:/e2e/.git
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js

  # TODO: add production/test profiles, we don't need a dev profile just yet
  # TODO: add seeding service, for testing
  # TODO: add healthcheck, I think this can stop `web` from starting until the database is up
  db:
    image: mongo:latest # TODO: insert actual mongo image name
    hostname: db
    tty: true
    environment:
      TERM: 'xterm-256color'
      # TODO: insert envvars for username password etc
      # TODO: insert envvars for storing database on volume
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  # TODO: figure out what will work for a production environment later
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    working_dir: /app
      #command: yarn dev
    command: yarn start:server
    environment:
      PORT: 3000
#volumes:
#mongodb:
#mongodb_config: # TODO: don't know if this is necessary

