# NOTE: this file is overridden for development by docker-compose.override.yml
version: '3.8'

services:
  # TODO add nginx and app containers
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      #command: tail -f /dev/null

  certbot:
    image: certbot/certbot:latest
    profiles: ['prod']
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./cerbot/conf/:/etc/letsencrypt/:rw

  # NOTE: this does not work on m1 macs, cypress is working on it, but it seems like it depends upon chrome creating a linux/arm64 release, which is unlikely
  cypress:
    image: cypress/included:10.3.0
    platform: "linux/amd64"
    profiles: ['test']
      #entrypoint: cypress open --project /
    depends_on:
      - web
    environment:
      CYPRESS_baseUrl: http://web:3000 # this bypasses nginx, I'm not sure if this is a good idea
    working_dir: /e2e
    volumes:
      #- ./:/e2e
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js

  # TODO: add production/test profiles, we don't need a dev profile just yet
  # TODO: add seeding service, for testing
  db:
    image: mongo:latest # TODO: insert actual mongo image name
    hostname: db
    tty: true
    environment:
      TERM: 'xterm-256color'
      # TODO: insert envvars for username password etc
      # TODO: insert envvars for storing database on volume
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  # TODO: figure out what will work for a production environment later
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    working_dir: /app
    command: yarn dev
    environment:
      PORT: 3000
#volumes:
#mongodb:
#mongodb_config: # TODO: don't know if this is necessary

