services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      #command: tail -f /dev/null

  certbot:
    image: certbot/certbot:latest
    profiles: ['prod']
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./cerbot/conf/:/etc/letsencrypt/:rw
