# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  working_directory: ~/project
  machine:
    image: ubuntu-2204:2022.04.1
    docker_layer_caching: true # NOTE: doesn't seem to do anything, follow up if you have time
  resource_class: medium

orbs:
  node: circleci/node@5.0.2

# TODO: end goal is for PRs into master to have testing done on them, and to run a test before making a release (main->release branch merge basically)
# NOTE: we want to run integration tests on the same image that is fit for production, should revisit and make sure of this
jobs:
  build_prod:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build application image
          # NOTE: everything else will be build during test
          command: "docker compose
                      --project-name signbank
                      -f docker-compose.yml -f docker-compose.prod.yml
                      build web"

  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build application image
          # TODO: set up image tagging, avoid `latest`, use semver
          command: "docker compose
                      --project-name signbank
                      -f docker-compose.yml -f docker-compose.prod.yml
                      build web"
      # TODO: configure cypress to run unit tests as well, no need to have two test runners
      - run:
          name: Run tests
          command: "docker compose
                      --project-name signbank
                      --profile test
                      -f docker-compose.yml -f docker-compose.prod.yml
                      up --exit-code-from cypress"
      - store_test_results:
          path: cypress
      # TODO: push to docker hub if the tests passed

  # TODO: reintroduce browserstack testing, not sure how that'll work with the new docker setup
  browserstack_tests:
    executor: node/default
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Download browserstack local binary
          command: wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
      - run:
          name: Unzip browserstack local binary
          command: unzip BrowserStackLocal-linux-x64.zip
      - run:
          name: Run browserstack local binary
          command: ./BrowserStackLocal $BROWSERSTACK_ACCESS_KEY
          background: true
      - run:
          name: Run integration tests
          command: yarn cypress:ci

workflows:
  integration_tests:
    jobs:
      - build_and_test

